### ISSUE TITLE
Getting SSL error on example

### ISSUE THREAD

**Issue by john3exonets** [thwi/node-icontrol#1]
Trying out the initial example, but getting what looks like an SSL error:

> bigip.list('/sys/software/image', function(err,res) {
> ... if (err) { console.log(err); }
> ... console.log(res);
> ... });
> undefined
> [Error: DEPTH_ZERO_SELF_SIGNED_CERT]
> false

Running this on Node.JS REPL session.   What am I doing wrong?  This is against BIG-IP v11.6 fresh install.

Thanks!

**Comment by john3exonets** [comment]
...And to answer my own issue:  "strict: true" sets up strict SSL cert checking. Setting it to 'false' disables the strict checking.

> bigip.strict = false;
> bigip.list('/sys/software/image', function(err,res) {
> ... if (err) { console.log(err); }
> ... console.log(res);
> ... });
> undefined
> [ { kind: 'tm:sys:software:image:imagestate',
>     name: 'BIGIP-11.6.0.0.0.401.iso',
>     fullPath: 'BIGIP-11.6.0.0.0.401.iso',
>     generation: 449,
>     selfLink: 'https://localhost/mgmt/tm/sys/software/image/BIGIP-11.6.0.0.0.401.iso?ver=11.6.0',
>     build: '0.0.401',
>     buildDate: 'Mon Aug 11 21 08 03 PDT 2014',
>     checksum: 'fb6cd17700c5f953dc363171d04d769c',
>     fileSize: '1955 MB',
>     lastModified: 'Mon Apr  20 14:23:37 2015',
>     product: 'BIG-IP',
>     verified: 'yes',
>     version: '11.6.0' } ]

undefined

**Comment by thwi** [comment]
Yep, strict SSL is enabled by default. :) Closing this issue.
