### ISSUE TITLE
Large outputs not returned??

### ISSUE THREAD

**Issue by john3exonets** [thwi/node-icontrol#2]
Trying to retrieve Licensing info, which is a rather large output, but the function call returns nothing:

> bigip.list('/shared/licensing/registration/', function(err,res) {
> ... if (err) { console.log(err); }
> ... console.log(res);
> ... });
> undefined
> undefined

No error, no nothing.  Suspect this is some kind of bug.

Object Dump:

> bigip
> { host: '192.168.59.105',
>   proto: 'https',
>   port: 443,
>   user: 'admin',
>   pass: 'admin',
>   strict: false,
>   url: '/mgmt/tm/shared/licensing/registration',
>   uri: 'https://192.168.59.105:443/mgmt/tm/shared/licensing/registration',
>   method: 'GET',
>   requestOpts:
>    { uri: 'https://192.168.59.105:443/mgmt/tm/shared/licensing/registration',
>      method: 'GET',
>      json: true,
>      auth: { user: 'admin', pass: 'admin' },
>      strictSSL: false,
>      rejectUnhauthorized: false } }

Using 'curl' against the same BIGIP works correctly:

> $ curl -sk -u admin:admin https://192.168.59.105/mgmt/tm/shared/licensing/registration -H 'Content-Type: applicaiton/json' -X GET | python -mjson.tool
> {
>     "activeModules": [
>         "LTM-VE, 3G|GLEFWCR-KKCXQNK|IPV6 Gateway|Rate Shaping|Ram Cache|50 MBPS COMPRESSION|SDN Services, VE|Routing Bundle, VE|Application Acceleration Manager, Core|Advanced Protocols, VE|SSL, 500 TPS Per Core|Anti-Virus Checks|Base Endpoint Security Checks|Firewall Checks|Network Access|Secure Virtual Keyboard|APM, Web Application|Machine Certificate Checks|Protected Workspace|Remote Desktop|App Tunnel|SSL, VE"
>     ],
>     "authVers": "5b",
>     "authorization": "8715b697b3658c08d...

**Comment by thwi** [comment]
Hi John, this should be fixed with the above commit and v0.1.5 has been published to NPM. I also added a 'debug' flag to the constructor that will output the HTTP request/response to make debugging easier in the future.
